# Generated by Django 3.0.8 on 2020-08-28 10:11

from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BerkasLaporan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_psu', models.CharField(max_length=100)),
                ('perumahan', models.CharField(max_length=100)),
                ('judul_laporan', models.CharField(max_length=100)),
                ('deskripsi_laporan', models.TextField()),
                ('bukti_foto_laporan', smartfields.fields.ImageField(blank=True, null=True, upload_to='laporan/foto')),
                ('bukti_video_laporan', smartfields.fields.FileField(blank=True, null=True, upload_to='laporan/video')),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
