# Generated by Django 3.1 on 2020-08-24 16:10

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkaslaporan',
            name='bukti_foto_laporan',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='laporan/dokumen/foto'),
        ),
        migrations.AlterField(
            model_name='berkaslaporan',
            name='bukti_video_laporan',
            field=smartfields.fields.FileField(blank=True, null=True, upload_to='laporan/dokumen/video'),
        ),
    ]
