# Generated by Django 3.1 on 2020-08-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='berkaslaporan',
            table='kelola_berkaslaporan',
        ),
    ]
