# Generated by Django 3.0.8 on 2020-09-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_skpd', '0001_initial'),
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkaslaporan',
            name='id_admin_penanganan_laporan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='admin_skpd.AdminSKPD'),
        ),
        migrations.AlterField(
            model_name='berkaslaporan',
            name='id_admin_status_laporan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='admin_skpd.AdminSKPD'),
        ),
    ]
