# Generated by Django 3.0.8 on 2020-09-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_auto_20200930_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='berkaslaporan',
            name='is_approve',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
