# Generated by Django 3.1 on 2020-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_auto_20200829_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berkaslaporan',
            old_name='bukti_foto_laporan',
            new_name='foto_laporan',
        ),
        migrations.RemoveField(
            model_name='berkaslaporan',
            name='bukti_video_laporan',
        ),
        migrations.RemoveField(
            model_name='berkaslaporan',
            name='judul_laporan',
        ),
        migrations.RemoveField(
            model_name='berkaslaporan',
            name='nama_psu',
        ),
        migrations.RemoveField(
            model_name='berkaslaporan',
            name='perumahan',
        ),
        migrations.AddField(
            model_name='berkaslaporan',
            name='bentuk_penanganan_laporan',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='berkaslaporan',
            name='id_admin_penanganan_laporan',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='berkaslaporan',
            name='id_admin_status_laporan',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='berkaslaporan',
            name='status_laporan',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='berkaslaporan',
            name='tanggal_entri_laporan',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='berkaslaporan',
            name='deskripsi_laporan',
            field=models.CharField(max_length=200),
        ),
    ]
