# Generated by Django 3.0.8 on 2020-09-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_auto_20200922_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkaslaporan',
            name='deskripsi_laporan',
            field=models.TextField(),
        ),
    ]
