# Generated by Django 3.1 on 2020-09-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_auto_20200902_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkaslaporan',
            name='id_admin_penanganan_laporan',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='berkaslaporan',
            name='id_admin_status_laporan',
            field=models.PositiveIntegerField(),
        ),
    ]
