# Generated by Django 3.0.8 on 2020-10-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_berkaslaporan_is_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='berkaslaporan',
            name='alasan_ditolak',
            field=models.TextField(blank=True, null=True),
        ),
    ]
