# Generated by Django 3.1 on 2020-10-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0004_berkaslaporan_alasan_ditolak'),
        ('laporan', '0002_auto_20200930_2113'),
    ]

    operations = [
    ]
