# Generated by Django 3.1.1 on 2020-10-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_merge_20201001_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berkaslaporan',
            options={'ordering': ['-id']},
        ),
    ]
