# Generated by Django 3.1 on 2020-09-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_berkaslaporan_nama_psu_laporan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkaslaporan',
            name='bentuk_penanganan_laporan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berkaslaporan',
            name='id_admin_penanganan_laporan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berkaslaporan',
            name='id_admin_status_laporan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berkaslaporan',
            name='tanggal_entri_laporan',
            field=models.DateField(auto_now_add=True),
        ),
    ]
