# Generated by Django 3.0.8 on 2020-09-19 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0007_berkaslaporan_judul_laporan'),
    ]

    operations = [
        migrations.AddField(
            model_name='berkaslaporan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='berkaslaporan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
