# Generated by Django 3.0.8 on 2020-10-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPerusahaan',
            fields=[
                ('id_data_perusahaan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_perusahaan', models.CharField(max_length=255)),
                ('akta_pendirian_badan_usaha', models.FileField(upload_to='akta_pendirian_badan_usaha')),
                ('nama_pemilik', models.CharField(max_length=255)),
                ('foto_pemilik', models.ImageField(upload_to='foto_pemilik')),
                ('ktp_pemilik', models.FileField(upload_to='ktp_pemilik')),
                ('bentuk_perusahaan', models.CharField(max_length=20)),
                ('alamat_perusahaan', models.CharField(max_length=255)),
                ('tahun_berdiri', models.IntegerField()),
                ('no_telp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
                ('verified_admin', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'pelaporan_dataperusahaan',
            },
        ),
        migrations.CreateModel(
            name='DataProyek',
            fields=[
                ('id_data_proyek', models.AutoField(primary_key=True, serialize=False)),
                ('lokasi_proyek', models.CharField(max_length=255)),
                ('luas_total_area_proyek', models.FloatField()),
                ('jumlah_total_unit', models.IntegerField()),
                ('jenis_produk', models.CharField(max_length=50)),
                ('jumlah_tipe_rumah', models.IntegerField()),
                ('target_pembangunan', models.IntegerField()),
                ('verified_tipe_rumah', models.BooleanField(default=False)),
                ('verified_jenis_psu', models.BooleanField(default=False)),
                ('verified_data_perizinan', models.BooleanField(default=False)),
                ('verified_admin_data_proyek', models.PositiveSmallIntegerField(default=0)),
                ('verified_admin_tipe_rumah', models.PositiveSmallIntegerField(default=0)),
                ('verified_admin_jenis_psu', models.PositiveSmallIntegerField(default=0)),
                ('verified_admin_data_perizinan', models.PositiveSmallIntegerField(default=0)),
                ('id_data_perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_proyek.DataPerusahaan')),
            ],
            options={
                'db_table': 'pelaporan_dataproyek',
            },
        ),
    ]
