# Generated by Django 3.1.1 on 2020-10-03 16:47

from django.db import migrations, models
import django.db.models.deletion
import e_psu.helpers
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_proyek', '0001_initial'),
        ('admin_kelola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', smartfields.fields.FileField(upload_to=e_psu.helpers.PathAndRename('serah_terima/dokumen/video/'))),
                ('foto', smartfields.fields.ImageField(upload_to=e_psu.helpers.PathAndRename('serah_terima/dokumen/foto/'))),
                ('salinan_laporan', smartfields.fields.FileField(upload_to=e_psu.helpers.PathAndRename('serah_terima/dokumen/salinan_laporan/'))),
                ('status_pengelolaan_text', models.CharField(blank=True, max_length=100)),
                ('pola_pengelolaan_text', models.CharField(blank=True, max_length=100)),
                ('regulasi_pemanfaatan_psu_text', models.CharField(blank=True, max_length=100)),
                ('status_pengelolaan', smartfields.fields.FileField(blank=True, null=True, upload_to=e_psu.helpers.PathAndRename('serah_terima/dokumen/status_pengelolaan/'))),
                ('pola_pengelolaan', smartfields.fields.FileField(blank=True, null=True, upload_to=e_psu.helpers.PathAndRename('serah_terima/dokumen/pola_pengelolaan/'))),
                ('regulasi_pemanfaatan_psu', smartfields.fields.FileField(blank=True, null=True, upload_to=e_psu.helpers.PathAndRename('serah_terima/dokumen/regulasi_pemanfaatan_psu/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_kelola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_kelola.adminkelola')),
                ('data_proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_proyek.dataproyek')),
            ],
            options={
                'db_table': 'kelola_serahterima',
                'ordering': ['-id'],
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
