# Generated by Django 3.1 on 2020-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_psu', models.CharField(max_length=100)),
                ('perumahan', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='serah_terima/dokumen/video/')),
                ('foto', models.ImageField(upload_to='serah_terima/dokumen/foto/')),
                ('salinan_laporan', models.FileField(upload_to='serah_terima/dokumen/salinan_laporan/')),
            ],
        ),
    ]
