# Generated by Django 3.0.8 on 2020-09-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serah_terima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='pola_pengelolaan_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='regulasi_pemanfaatan_psu_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='status_pengelolaan_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
