# Generated by Django 3.1 on 2020-08-22 12:33

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serah_terima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='foto',
            field=smartfields.fields.ImageField(upload_to='serah_terima/dokumen/foto/'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='salinan_laporan',
            field=smartfields.fields.FileField(upload_to='serah_terima/dokumen/salinan_laporan/'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='video',
            field=smartfields.fields.FileField(upload_to='serah_terima/dokumen/video/'),
        ),
    ]
