# Generated by Django 3.0.8 on 2020-09-19 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serah_terima', '0002_auto_20200918_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokumen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
