# Generated by Django 3.1.1 on 2020-10-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warga', '0001_initial'),
        ('data_proyek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerwakilanPenghuni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_proyek.dataproyek')),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga.warga')),
            ],
            options={
                'db_table': 'kelola_perwakilanpenghuni',
            },
        ),
    ]
