# Generated by Django 3.1.1 on 2020-10-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perwakilan_penghuni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perwakilanpenghuni',
            options={'ordering': ['-id']},
        ),
    ]
