# Generated by Django 3.1 on 2020-09-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perwakilan_penghuni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perwakilanpenghuni',
            name='no_ktp',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
