# Generated by Django 3.1 on 2020-10-04 19:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ktp', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='KTP harus mempunyai 16 digit angka', regex='\\d{16}$')])),
                ('nama', models.CharField(max_length=30)),
                ('alamat_rumah', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kelola_warga',
            },
        ),
    ]
