# Generated by Django 3.0.8 on 2020-08-28 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('no_ktp', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=30)),
                ('alamat_rumah', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kelola_warga',
            },
        ),
    ]
