# Generated by Django 3.0.8 on 2020-09-22 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='no_ktp',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='KTP harus mempunyai 16 digit', regex='\\d{16}$')]),
        ),
    ]
