# Generated by Django 3.0.8 on 2020-09-23 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_auto_20200922_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='no_ktp',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='KTP harus mempunyai 16 digit angka', regex='\\d{16}$')]),
        ),
    ]
